### ISSUE TITLE
Plugin is activated but it says it's not.

### ISSUE THREAD

**Issue by mairagall** [keesiemeijer/related-posts-by-taxonomy-cache#1]
Hi, just wanted to test this plugin and after activating it, I see this message: 

`http://puu.sh/s5jHR/07663fc025.png

**Comment by keesiemeijer** [comment]
Just to be sure, did you install and activate this plugin also?
https://github.com/keesiemeijer/related-posts-by-taxonomy

**Comment by mairagall** [comment]
Hi, nop, will check that out.
Thanks!

2016-11-04 9:46 GMT-03:00 Kees Meijer notifications@github.com:

**Comment by keesiemeijer** [comment]
No problem.

Here is more information about the cache
https://keesiemeijer.wordpress.com/related-posts-by-taxonomy/cache/

The readme for this plugin will be updated to make it more clear what's needed for this plugin to work.
